---

- hosts: stapp01
  become: yes
  tasks:
    - name: Create empty file
      file:
        path: /opt/itadmin/blog.txt
        state: touch
        owner: tony
        group: tony
    - name: Create symbolic link
      file:
        state: link
        src: /opt/itadmin
        dest: /var/www/html

- hosts: stapp02
  become: yes
  tasks:
    - name: Create empty file
      file:
        path: /opt/itadmin/story.txt
        state: touch
        owner: steve
        group: steve
    - name: Create symbolic link
      file:
        state: link
        src: /opt/itadmin
        dest: /var/www/html

- hosts: stapp03
  become: yes
  tasks:
"playbook.yml" 47L, 919C
