---
- name: creating backup and copying this to servers
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
  - name: creating archive beta.tar.gz
    archive:
      path: /usr/src/dba/
      dest: /opt/dba/beta.tar.gz
      format: gz
      force_archive: true
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
